color:
  brandStrength: 0.625
  saturation: 0.3125
  brandColors:
    - '#161d23'
    - '#6a6854'
    - '#cbc7a0'
    - '#b1ac83'
    - '#f7f9e5'
  lightness: 0.625
  rhythmicContrast: 0.5
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.57426
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose:
  - item: null
    name: awareness
    url: null
name: '365'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.46436
