name: '365'
favicon: null
layout_spectrum: 0.57426
typography_spectrum: 0.46436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161d23'
    - '#6a6854'
    - '#cbc7a0'
    - '#b1ac83'
    - '#f7f9e5'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
